contacts/urls.py
from django.urls import path
from contacts import views

app_name = 'contacts'
urlpatterns = [   
    path('search/',views.search, name='search'),
    path('', views.index, name='index'),

    #contact CRUD
    path('contact/<int:cont_id>', views.single_contact, name='single_contact'),
    path('contact/create', views.create, name='create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('contacts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

contacts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank = True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=255, blank=True)
    created_date = models.DateTimeField(default=timezone.now())
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m')
    category = models.ForeignKey(Category, blank=True, on_delete=models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contacts/forms.py
from django.core.exceptions import ValidationError
from django import forms
from contacts.models import Contact

class ContactForm(forms.ModelForm):
    
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            

            if field == 'first_name':
                ...
            else:
                self.fields[field].widget.attrs.update({
                    'placeholder':'Escreva aqui'
                })

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder':'Escreva aqui'
            },
        ),
        help_text='Escreva seu primeiro nome'
    )

    class Meta:
        model = Contact
        fields = ['first_name','last_name','phone','email','description','category']

    def clean(self):
        cleaned_data = self.cleaned_data
        
        if cleaned_data['first_name'] == cleaned_data['last_name']:
            self.add_error(
                None,
                ValidationError(
                    'Primeiro nome igual ao segundo',
                    code='invalid'
                )
            )
        return super().clean()
    
    

contacts/views.py
from django.shortcuts import render

# Create your views here.

def contacts(requests):
    return render(
        requests,
        'contacts/index.html'
        )

contacts/views/contact_forms.py
from django.shortcuts import render, redirect
from contacts.forms import ContactForm
# Create your views here.


def create(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        context={
            'form':form,
        }
        
        if form.is_valid():
            # contact = form.save(commit = False)
            # contact.show = False
            form.save()
            return redirect('contacts:create')
            
        return render(
            request,
            'contacts/create.html',
            context=context,
        )

    form = ContactForm()
    context = {
        'form':form
    }

    return render(
        request,
        'contacts/create.html',
        context=context
        )

contacts/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from contacts.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator
# Create your views here.

def index(requests):
    #contact_ = Contact.objects.all()
    contact_ = Contact.objects \
        .filter(show=True)\
        .order_by('id')
    paginator = Paginator(contact_,10)
    page_number = requests.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'index_title':'Contato - ',
        'page_obj': page_obj,
    }
    return render(
        requests,
        'contacts/index.html',
        context=context
        )

def single_contact(requests,cont_id):
    #contact_ = Contact.objects.filter(id=cont_id).first()
    contact_ = get_object_or_404(Contact, id=cont_id, show=True)
    
    name_title = contact_.first_name
    context = {
        'contact': contact_,
        'contact_title': f'{name_title} - ',
    }
    
    return render(
        requests,
        'contacts/contact.html',
        context=context,
        )

def search(request):
    search_query = request.GET.get('q','').strip()
    print(request.GET.get('q',''))
    if search_query == '':
        return redirect('contacts:index')
    
    contact_ = Contact.objects \
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_query) |
            Q(last_name__icontains=search_query) |
            Q(phone__icontains=search_query) |
            Q(email__icontains=search_query)
            )\
        .order_by('id')
    
    paginator = Paginator(contact_,10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'contact_title': f'Search - ',
        'search_query': search_query,
    }

    return render(
        request,
        'contacts/index.html',
        context

    )

contacts/templates/contacts/contact.html
{% extends "base.html" %}

{% block index %}
<div class="single-content">
    <h1 class="single-content-name">
        {{contact.first_name}} {{contact.last_name}}
    </h1>

    <p><b>ID: </b> {{contact.id}}</p>
    <p><b>E-mail: </b> {{contact.email}}</p>
    <p><b>Phone: </b> {{contact.phone}}</p>
    <p><b>Created Date: </b> {{contact.created_date}}</p>
    <p><b>Description: </b> {{contact.description}}</p>
    <p><b>Category</b> {{contact.category.name}}</p>

</div>


{% endblock index %}

contacts/templates/contacts/create.html
{% extends "base.html" %}

{% block create %}
    <div class="form-wrapper">
        <h2>Contact</h2>

        <form 
        action="" 
        method="POST" 
        enctype="multipart/form-data"
        >

        {% csrf_token %}
        
        <div class="form-content">
            <div class="form-group">
                {% for field in form %}
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                    {{field}}
                    {{field.errors}}
                    {% if field.help_text %}
                        <p class='help-text'>{{field.help_text}}</p>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        
        {% if form.non_field_errors %}
            <div class="form-content">
                <div class="form-group">
                    <div class="message error">
                        {{form.non_field_errors}}
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">Send</button>
            </div>
        </div>


        
        </form>
    </div>
{% endblock create %}

contacts/templates/contacts/index.html
{% extends "base.html" %}

{% block index %}
    {% if page_obj %}    
    <div class="responsible-table">
        <table class="contacts-table">
            <caption class="table-caption">Contacts</caption>
        
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">First Name</th>
                    <th class="table-header">Last Name</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">E-mail</th>
                </tr>
            </thead>

            <tbody>
                {% for cont in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a href={% url "contacts:single_contact" cont.id  %} class="table-link">
                                {{cont.id}}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{cont.first_name}}
                        </td>
                        <td class="table-cel">
                            {{cont.last_name}}
                        </td>
                        <td class="table-cel">
                            {{cont.phone}}
                        </td>
                        <td class="table-cel">
                            {{cont.email}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <div class="single-content">
            <h1 class="single-content-name">
                Contato não encontrado
            </h1>
        </div>
    {% endif %} 
{% endblock index %}